package cn.shineiot.base.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.shineiot.base.bean.AndroidArticle;
import cn.shineiot.base.bean.User;

import cn.shineiot.base.greedao.AndroidArticleDao;
import cn.shineiot.base.greedao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig androidArticleDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AndroidArticleDao androidArticleDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        androidArticleDaoConfig = daoConfigMap.get(AndroidArticleDao.class).clone();
        androidArticleDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        androidArticleDao = new AndroidArticleDao(androidArticleDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(AndroidArticle.class, androidArticleDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        androidArticleDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AndroidArticleDao getAndroidArticleDao() {
        return androidArticleDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
