package cn.shineiot.base.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.shineiot.base.bean.AndroidArticle;

import cn.shineiot.base.greedao.AndroidArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig androidArticleDaoConfig;

    private final AndroidArticleDao androidArticleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        androidArticleDaoConfig = daoConfigMap.get(AndroidArticleDao.class).clone();
        androidArticleDaoConfig.initIdentityScope(type);

        androidArticleDao = new AndroidArticleDao(androidArticleDaoConfig, this);

        registerDao(AndroidArticle.class, androidArticleDao);
    }
    
    public void clear() {
        androidArticleDaoConfig.clearIdentityScope();
    }

    public AndroidArticleDao getAndroidArticleDao() {
        return androidArticleDao;
    }

}
